<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Beer;

/**
 * BeerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Beer $beer
     */
    public function persist(Beer $beer)
    {
        $em = $this->getEntityManager();
        $em->persist($beer);
        $em->flush();
    }
}
