<?php

namespace AppBundle\Repository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $mac
     * @return mixed
     */
    public function findByMac(string $mac)
    {
        $query = $this->createQueryBuilder('d')
            ->where('d.mac = :mac')
            ->setParameter('mac', $mac)
            ->getQuery();
        return $query->getSingleResult();
    }    
}
