<?php

namespace AppBundle\Repository;

/**
 * LogDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogDataRepository extends \Doctrine\ORM\EntityRepository
{
}
