# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Service\:
        resource: '../../src/AppBundle/Service/*'
        public: true

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Repository\BeerRepository:
        factory: doctrine.orm.entity_manager:getRepository
        arguments:
            - AppBundle\Entity\Beer
        public: true
    AppBundle\Repository\DeviceRepository:
        factory: doctrine.orm.entity_manager:getRepository
        arguments:
            - AppBundle\Entity\Device
        public: true
    AppBundle\Repository\MeasurementRepository:
        factory: doctrine.orm.entity_manager:getRepository
        arguments:
            - AppBundle\Entity\Measurement
        public: true
