services:
  log_data.factory:
    class: AppBundle\Service\LogDataFactory
  device.factory:
    class: AppBundle\Service\DeviceFactory
  tracker:
    class: AppBundle\Service\Tracker
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@log_data.factory'
      - '@device.factory'